### ISSUE TITLE
osc user authentification seems to be broken with last commit

### ISSUE THREAD

**Issue by kkeil** [openSUSE/osc#202]
with current master for example  this does not longer work
`osc -c ~/testobsadmin.rc meta prjconf  Test10 -F newprjconf
Sending meta data...
Server returned an error: HTTP Error 500: Internal Server Error

Request: https://api.linux-pingi.de/source/Test10/_config
Headers:
content-language: en
accept-ranges: bytes
vary: accept-language,accept-charset
server: Apache
connection: close
cache-control: public
date: Sat, 28 May 2016 10:42:35 GMT
content-type: text/html; charset=utf-8
`
Same command with 0.154.0  works, a quick bisect found 
[c53a7681](https://github.com/openSUSE/osc/commit/c53a7681ef289181b03e1077efbfd246bf1247f6) as reason.

**Comment by marcus-h** [comment]
Hmm I cannot reproduce this:

marcus@linux:~> osc meta prjconf home:Marcus_H > prjconf
marcus@linux:~> echo >> prjconf 
marcus@linux:~> osc meta prjconf home:Marcus_H -F prjconf
Sending meta data...
Done.
marcus@linux:~>

Can you post the output of
"osc -d -c ~/testobsadmin.rc meta prjconf  Test10 -F newprjconf"?

**Comment by mmohring** [comment]
I can reproduce this:

`> osc -A https://api.myobsapi.com meta prj -F OBS:Tools:Unstable.xml OBS:Tools:Unstable`

returns:

`Sending meta data...
Server returned an error: HTTP Error 500: Internal Server Error

Request: https://api.openlifecyclemanager.com/source/OBS%3ATools%3AUnstable/_meta
Headers:
content-language: en
accept-ranges: bytes
vary: accept-language,accept-charset
server: Apache
connection: close
cache-control: public
date: Sun, 29 May 2016 18:04:51 GMT
content-type: text/html; charset=utf-8
`

while the git commit 8466e49d59a9b6375943807a55564d7071689b0c works.

**Comment by mmohring** [comment]
I checked with git commit c53a7681ef289181b03e1077efbfd246bf1247f6 , which returns this error.

**Comment by mmohring** [comment]
Still happens with git commit 502dbaa030a13d48184eafec5d1fe3c3378af1fb the current git master.

**Comment by marcus-h** [comment]
On 2016-05-29 11:15:45 -0700, Martin Mohring wrote:
> I can reproduce this:
> 
> `> osc -A https://api.myobsapi.com meta prj -F OBS:Tools:Unstable.xml OBS:Tools:Unstable`
> 
Can you please run this with the "-d" option in front?

**Comment by kkeil** [comment]
[osc.txt](https://github.com/openSUSE/osc/files/288923/osc.txt)
This is the output of osc -d. The API server side is 2.6.9. 

I can confirm, that it seems to still work with opensuse.org, maybe thats because of the ichain/proxy auth.

The error on the OBS server is (production.log):
`
f815ad91-4a78-45e3-94ec-60fd87a108a4] [13149:142176.01] Started PUT "/source/Test1/_config" for 10.23.200.0 at 2016-05-30 08:08:08 +0200
[f815ad91-4a78-45e3-94ec-60fd87a108a4] [13149:142176.01] Processing by SourceController#update_project_config as XML
[f815ad91-4a78-45e3-94ec-60fd87a108a4] [13149:142176.01]   Parameters: {"project"=>"Test1"}
[f815ad91-4a78-45e3-94ec-60fd87a108a4] [13149:142176.01] Can't verify CSRF token authenticity
[f815ad91-4a78-45e3-94ec-60fd87a108a4] [13149:142176.02]   Rendered status.xml.builder (0.3ms)
[f815ad91-4a78-45e3-94ec-60fd87a108a4] [13149:142176.02] Completed 401 Unauthorized in 5ms (Views: 1.1ms | ActiveRecord: 0.7ms | Backend: 0.0ms | XML: 0.0ms)
`

**Comment by marcus-h** [comment]
On 2016-05-29 23:43:25 -0700, Karsten Keil wrote:
> 
> [osc.txt](https://github.com/openSUSE/osc/files/288923/osc.txt)
> This is the output of osc -d. The API server side is 2.6.9. 
> 
Ah sorry, I was thinking about "-H", but I was writing "-d"...
can you also post the output of "osc -d -H ..." :)

**Comment by kkeil** [comment]
[osc_d_h_fail.txt](https://github.com/openSUSE/osc/files/289227/osc_d_h_fail.txt)
[osc_d_h_OK.txt](https://github.com/openSUSE/osc/files/289228/osc_d_h_OK.txt)
I did it with `osc -d --http-full-debug -c ~/testobsadmin.rc meta prjconf  Test1 -F /tmp/new.prjconf` since this is an internal test instance. OK is without commit c53a768.

**Comment by adrianschroeter** [comment]
@mmohring is the 500 reproducable? In that case I would be interessted in the backtrace of the api. (no client should be able to create this)

**Comment by mmohring** [comment]
@adrianschroeter Will make a log and put it here. Will try with my local OBS and b.o.o.

**Comment by kkeil** [comment]
@adrian yes I see the 500 too, but here is no back trace in the production.log, only what I wrote in the comment above. in the access log I see the 500:
`10.23.200.0 - - [30/May/2016:10:59:23 +0200] "PUT /source/Test1/_config HTTP/1.1" 401 112
10.23.200.0 - - [30/May/2016:10:59:23 +0200] "PUT /source/Test1/_config HTTP/1.1" 500 1013
`

**Comment by marcus-h** [comment]
On 2016-05-30 02:10:35 -0700, Karsten Keil wrote:
> [osc_d_h_fail.txt](https://github.com/openSUSE/osc/files/289227/osc_d_h_fail.txt)
> [osc_d_h_OK.txt](https://github.com/openSUSE/osc/files/289228/osc_d_h_OK.txt)
> I did it with `osc -d --http-full-debug -c ~/testobsadmin.rc meta prjconf  Test1 -F /tmp/new.prjconf` since this is an internal test instance. OK is without commit c53a768.
> 
Thanks! From a first glance, the logs look good:

osc_d_h_fail.txt:
...
send: <open file '/tmp/osc_metafile.M4gVHU.txt', mode 'rb' at 0x7f80540d85d0>
sendIng a read()able
...

indicates that the correct codepath is used (in this case).
The only difference between the two codepaths is the way how the data
is send to the server (one big "chunk" vs. several "small" "chunks"
(from a high-level perspective))... it seems that the latter might
confuse the apache.

I'll try to reproduce with a local obs instance (as soon as I have it
running again).

**Comment by mmohring** [comment]
First of all the check with b.o.o.

`> rpm -qa | grep osc`
`osc-0.155.git.1464531661.502dbaa-18.1.noarch`

`> osc -A https://api.opensuse.org meta prj -F home:MartinMohring:Base:build:arm.xml home:MartinMohring:Base:build:arm`
`Sending meta data...`
`Done.`

So this works.

**Comment by mmohring** [comment]
Now the output of:

`osc -d -H -A https://api.openlifecyclemanager.com meta prj -F OBS:Server:Unstable.xml OBS:Server:Unstable >& a.log`

Attached
[a.log.txt](https://github.com/openSUSE/osc/files/289361/a.log.txt)

And the server side log also attached
[b.log.txt](https://github.com/openSUSE/osc/files/289362/b.log.txt)

**Comment by mmohring** [comment]
I am using openSUSE 13.2 x86_64 as a host for OBS Unstable. Installed git master from git commit 54314f6e74235292a0de902534a1cba5993b1beb , e.g. from Friday. As I said osc git commit c53a7681ef289181b03e1077efbfd246bf1247f6 was when it started not working.

**Comment by mmohring** [comment]
I will test https://github.com/openSUSE/open-build-service/pull/1840 .

**Comment by mmohring** [comment]
I have tested openSUSE/open-build-service#1840 , still the same results.

**Comment by adrianschroeter** [comment]
1840 is unrelated to this issue

**Comment by mmohring** [comment]
OK. Anyway, I have tried to accidentially make a osc ci with also an internal 500 error:

`> osc ci -m"fixed: make revisioned meta working causing a 500 by current osc git master"`

and this resulted also in an error:

[c.log.txt](https://github.com/openSUSE/osc/files/289707/c.log.txt)

**Comment by kkeil** [comment]
@marcus-h: I tried this against the last unstable appliance  (obs-server qcow2 image), same results.

**Comment by marcus-h** [comment]
On 2016-06-01 05:13:36 -0700, Karsten Keil wrote:
> @marcus-h: I tried this against the last unstable appliance  (obs-server qcow2 image), same results.
> 
For now, I reverted the commit again (it also broke the python 3.4
support) (see commit acbd2c17c7649c825f3afb6593aec8df1e77c6ca).
I won't close this issue, because it definitely needs further debugging
(I'll have look at it ASAP).

**Comment by abitrolly** [comment]
Is this still broken?
